apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # main container - can communicate with main container via http://localhost:9113
  # runs nginx stuff
  - name: main-ctr
    image: nigelpoulton/nginxadapter:1.0
    ports:
    - containerPort: 80
  # helper container - can communicate with main container via http://localhost:80
  # exposes nginx logs in a format required for prometheus
  - name: helper-ctr
    image: nginx/nginx-prometheus-exporter
    args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
    ports:
    - containerPort: 9113