name: tester

on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
          cache: pip
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: python -B -m pytest
